# Generated by Django 5.0.1 on 2024-02-07 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='suspiciousactivities',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='suspiciousactivities',
            name='time',
            field=models.CharField(max_length=100),
        ),
    ]
