# Generated by Django 5.0.1 on 2024-02-07 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_chat_date_alter_complaints_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='USER',
        ),
        migrations.AddField(
            model_name='review',
            name='LOGIN',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.login'),
            preserve_default=False,
        ),
    ]
