# Generated by Django 5.0.1 on 2024-02-07 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_review_user_review_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='LOGIN',
        ),
        migrations.AddField(
            model_name='review',
            name='USER',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.user'),
            preserve_default=False,
        ),
    ]
