# Generated by Django 5.0.1 on 2024-02-07 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_review_login_review_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='FROM_ID',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='TO_ID',
        ),
        migrations.AddField(
            model_name='chat',
            name='FROMID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fuser', to='myapp.login'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chat',
            name='TOID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tuser', to='myapp.login'),
            preserve_default=False,
        ),
    ]
