# Generated by Django 5.0.1 on 2024-02-10 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_chat_from_id_remove_chat_to_id_chat_fromid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='detect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=100)),
                ('CRIMINAL', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.criminals')),
            ],
        ),
    ]
