# Generated by Django 5.0.1 on 2024-02-10 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_detect'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detect',
            name='CRIMINAL',
        ),
        migrations.AddField(
            model_name='detect',
            name='image',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='detect_sub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CRIMINAL', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.criminals')),
                ('DETECT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.detect')),
            ],
        ),
    ]
