# Generated by Django 2.2.24 on 2024-03-07 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20240305_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='detection',
            name='photo',
            field=models.CharField(default='', max_length=100),
        ),
    ]
