# Generated by Django 2.2.24 on 2024-03-08 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_detection_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='detection',
            name='message',
            field=models.CharField(default='', max_length=100),
        ),
    ]
