# Generated by Django 2.2.24 on 2024-03-10 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_auto_20240310_1233'),
    ]

    operations = [
        migrations.DeleteModel(
            name='detection',
        ),
    ]
