# Generated by Django 2.2.24 on 2024-03-10 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_detection'),
    ]

    operations = [
        migrations.DeleteModel(
            name='detection',
        ),
    ]
