# Generated by Django 2.2.24 on 2024-03-16 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_anonymous_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='criminals',
            name='threatlevel',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
