# Generated by Django 2.2.24 on 2024-03-17 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_criminals_threatlevel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suspiciousactivities',
            name='CRIMINAL',
        ),
    ]
